In [2]:
import pandas as pd
import numpy as np


import warnings 
warnings.filterwarnings('ignore')

In [260]:
def answer_one():
# ENERGY
    Energy = pd.read_excel('Energy Indicators.xls')
    header_drop = list(range(0,17))
    Energy.drop(header_drop, inplace = True)
    footer_drop = list(range(244,282))
    Energy.drop(footer_drop, inplace = True)
    Energy.drop(['Unnamed: 0', 'Unnamed: 1'], axis = 1, inplace = True)
    translate_cols = {
            'Unnamed: 2' : 'Country' ,
            'Unnamed: 3' : 'Energy Supply' ,
            'Unnamed: 4' : 'Energy Supply per Capita',
            'Unnamed: 5' : '% Renewable'
        }
    Energy.rename(columns = translate_cols, inplace = True)  
    Energy['Country'].replace('( \(.*\))','', regex=True, inplace = True)
    Energy['Country'].replace('(\d+)','', regex=True, inplace = True)   
    Energy['Country'] = Energy['Country'].str.strip()    
    for col in Energy:
        Energy[col] = Energy[col].replace('...',np.nan)       
    Energy['Energy Supply'] = Energy['Energy Supply'] * 1000000   
    Energy['Country'] = Energy['Country'].str.replace('Republic of Korea','South Korea')
    Energy['Country'] = Energy['Country'].str.replace('United States of America','United States')
    Energy['Country'] = Energy['Country'].str.replace('United Kingdom of Great Britain and Northern Ireland','United Kingdom')
    Energy['Country'] = Energy['Country'].str.replace('China, Hong Kong Special Administrative Region','Hong Kong')


    #GDP
    GDP = pd.read_csv('world_bank.csv', header = 3)
    GDP.columns = GDP.iloc[0]
    GDP.drop(0, inplace = True)       
    GDP.rename(columns = {'Country Name' : 'Country'}, inplace = True)
    GDP['Country'] = GDP['Country'].str.replace('Korea, Rep.','South Korea')
    GDP['Country'] = GDP['Country'].str.replace('Iran, Islamic Rep.','Iran')
    GDP['Country'] = GDP['Country'].str.replace('Hong Kong SAR, China','Hong Kong')    
    GDP = GDP.drop(GDP.iloc[:,1:50], axis=1)    
    GDP.columns = GDP.columns.astype(str).str.split('.').str[0]



    #ScimEn
    ScimEn = pd.read_excel('scimagojr-3.xlsx')



    #Inner Join
    merge1 = pd.merge(Energy, GDP, 'inner', 'Country')
    merge2 = pd.merge(merge1, ScimEn, 'inner', 'Country')
    df = merge2
    df = df.sort_values(by = ['Rank'])
    df.set_index('Country', inplace = True)
    cols1 = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015' ]
    df = df[cols1]

    #TOP 15
    df = df.head(15)
    return df

In [302]:
def answer_two():
    # ENERGY
    Energy = pd.read_excel('Energy Indicators.xls')
    header_drop = list(range(0,17))
    Energy.drop(header_drop, inplace = True)
    footer_drop = list(range(244,282))
    Energy.drop(footer_drop, inplace = True)
    Energy.drop(['Unnamed: 0', 'Unnamed: 1'], axis = 1, inplace = True)
    translate_cols = {
            'Unnamed: 2' : 'Country' ,
            'Unnamed: 3' : 'Energy Supply' ,
            'Unnamed: 4' : 'Energy Supply per Capita',
            'Unnamed: 5' : '% Renewable'
        }
    Energy.rename(columns = translate_cols, inplace = True)  
    Energy['Country'].replace('( \(.*\))','', regex=True, inplace = True)
    Energy['Country'].replace('(\d+)','', regex=True, inplace = True)   
    Energy['Country'] = Energy['Country'].str.strip()    
    for col in Energy:
        Energy[col] = Energy[col].replace('...',np.nan)       
    Energy['Energy Supply'] = Energy['Energy Supply'] * 1000000   
    Energy['Country'] = Energy['Country'].str.replace('Republic of Korea','South Korea')
    Energy['Country'] = Energy['Country'].str.replace('United States of America','United States')
    Energy['Country'] = Energy['Country'].str.replace('United Kingdom of Great Britain and Northern Ireland','United Kingdom')
    Energy['Country'] = Energy['Country'].str.replace('China, Hong Kong Special Administrative Region','Hong Kong')


    #GDP
    GDP = pd.read_csv('world_bank.csv', header = 3)
    GDP.columns = GDP.iloc[0]
    GDP.drop(0, inplace = True)       
    GDP.rename(columns = {'Country Name' : 'Country'}, inplace = True)
    GDP['Country'] = GDP['Country'].str.replace('Korea, Rep.','South Korea')
    GDP['Country'] = GDP['Country'].str.replace('Iran, Islamic Rep.','Iran')
    GDP['Country'] = GDP['Country'].str.replace('Hong Kong SAR, China','Hong Kong')    
    GDP = GDP.drop(GDP.iloc[:,1:50], axis=1)    
    GDP.columns = GDP.columns.astype(str).str.split('.').str[0]



    #ScimEn
    ScimEn = pd.read_excel('scimagojr-3.xlsx')



    #Inner Join
    merge1 = pd.merge(Energy, GDP, 'inner', 'Country')
    inner = pd.merge(merge1, ScimEn, 'inner', 'Country')

    #Outer Join
    merge1 = pd.merge(Energy, GDP, 'outer', 'Country')
    outer = pd.merge(merge1, ScimEn, 'outer', 'Country')

    result = outer.shape[0] - inner.shape[0]

    return result

In [207]:


GDP = pd.read_csv('world_bank.csv', header = 3)
GDP.columns = GDP.iloc[0]
GDP.drop(0, inplace = True)       
GDP.rename(columns = {'Country Name' : 'Country'}, inplace = True)
GDP['Country'] = GDP['Country'].str.replace('Korea, Rep.','South Korea')
GDP['Country'] = GDP['Country'].str.replace('Iran, Islamic Rep.','Iran')
GDP['Country'] = GDP['Country'].str.replace('Hong Kong SAR, China','Hong Kong')    
GDP = GDP.drop(GDP.iloc[:,1:50], axis=1)    
GDP.columns = GDP.columns.astype(str).str.split('.').str[0]

avgGDP = []
for item in range(GDP.shape[0]):
    mean = GDP.iloc[item, 1:11].mean()
    avgGDP.append(mean)
    

GDP['avgGDP'] = avgGDP

GDP = GDP.dropna()

ScimEn = pd.read_excel('scimagojr-3.xlsx')
ScimEn

df = pd.merge(GDP, ScimEn, 'inner', 'Country')

cols = ['Country', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', 'avgGDP']

GDP = df.sort_values(by = 'avgGDP', ascending = False)
GDP = GDP.set_index('Country')
result = GDP['avgGDP']

result = result.head(15)
GDP

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,avgGDP,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
Country,,,,,,,,,,,,,,,,,,
United States,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,1.536434e+13,2,96661,94747,792274,265436,8.20,230
China,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,6.348609e+12,1,127050,126767,597237,411683,4.70,138
Japan,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,5.542208e+12,3,30504,30287,223024,61554,7.31,134
Germany,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,3.493025e+12,7,17027,16831,140566,27426,8.26,126
France,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,2.681725e+12,9,13153,12973,130632,28601,9.93,114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Liberia,9.858721e+08,1.079874e+09,1.157052e+09,1.218377e+09,1.292697e+09,1.398698e+09,1.510516e+09,1.641990e+09,1.653503e+09,1.658424e+09,1.359700e+09,177,1,1,1,0,1.00,1
Antigua and Barbuda,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,1.159999e+09,1.155982e+09,1.211723e+09,1.256122e+09,1.230559e+09,169,2,2,0,0,0.00,0
Seychelles,8.566842e+08,9.459630e+08,9.256542e+08,9.154234e+08,9.699365e+08,1.046438e+09,1.115610e+09,1.183103e+09,1.222346e+09,1.265101e+09,1.044626e+09,172,2,2,7,2,3.50,1
Samoa,6.393881e+08,6.798143e+08,6.866743e+08,6.536571e+08,6.567891e+08,6.947420e+08,6.975356e+08,6.840462e+08,6.922284e+08,7.035448e+08,6.788420e+08,166,3,3,13,1,4.33,1
Palau,2.074094e+08,2.072990e+08,1.957150e+08,1.779528e+08,1.838000e+08,1.930672e+08,1.992454e+08,1.943911e+08,2.026654e+08,2.216412e+08,1.983187e+08,186,1,1,0,0,0.00,0

In [303]:
def answer_three():  
    top15 = answer_one()
    top15.columns
    cols = ['2006', '2007', '2008',
           '2009', '2010', '2011', '2012', '2013', '2014', '2015']
    top15 = top15[cols]

    avgGDP = []
    for item in range(top15.shape[0]):
        mean = top15.iloc[item, 0:11].mean()
        avgGDP.append(mean)

    top15['avgGDP'] = avgGDP

    return top15.sort_values(by = 'avgGDP', ascending = False)['avgGDP']

In [322]:
def answer_four():
    gdp_2006 = answer_one().loc[answer_three().to_frame().index[5]][10]
    gdp_2015 = answer_one().loc[answer_three().to_frame().index[5]][-1]

    return gdp_2015 - gdp_2006

In [360]:
def answer_five():
    return answer_one()['Energy Supply per Capita'].mean()

In [361]:
def answer_six():
    df = answer_one()['% Renewable']
    df = df.sort_values(ascending = False)
    return (df.index[0], df[0])

In [381]:
def answer_seven():
    df = answer_one()
    df['Ratio Citations'] = df['Self-citations'] / df['Citations']
    df = df['Ratio Citations']
    df = df.sort_values(ascending = False)
    return (df.index[0], df[0])

In [405]:
def answer_eight():
    df = answer_one()
    df = df[['Energy Supply', 'Energy Supply per Capita']]
    df['Population'] = df['Energy Supply'] / df['Energy Supply per Capita']
    df = df['Population']
    return df.sort_values(ascending = False).index[2]

In [423]:
def answer_nine():
    df = answer_one()
    df['Population'] = df['Energy Supply'] / df['Energy Supply per Capita']
    df['Citable docs per Capita'] = df['Citable documents'] / df['Population']
    df = df[['Citable docs per Capita', 'Energy Supply per Capita']]
    return df.corr().iloc[0][1]

In [440]:
df = answer_one()
median = df['% Renewable'].median()
numbers = []
for value in df['% Renewable']:
    if value >= median:
        numbers.append(1)
    else:
        numbers.append(0)

df['Above Median'] = numbers
HighRenew = df['Above Median']

In [443]:
def answer_ten():
    df = answer_one()
    median = df['% Renewable'].median()
    numbers = []
    for value in df['% Renewable']:
        if value >= median:
            numbers.append(1)
        else:
            numbers.append(0)

    df['Above Median'] = numbers
    HighRenew = df['Above Median']
    return HighRenew

In [483]:
def answer_eleven():
    df = answer_one()
    df['Population'] = df['Energy Supply'] / df['Energy Supply per Capita']
    df = df['Population']

    ContinentDict  = {'China':'Asia', 
                      'United States':'North America', 
                      'Japan':'Asia', 
                      'United Kingdom':'Europe', 
                      'Russian Federation':'Europe', 
                      'Canada':'North America', 
                      'Germany':'Europe', 
                      'India':'Asia',
                      'France':'Europe', 
                      'South Korea':'Asia', 
                      'Italy':'Europe', 
                      'Spain':'Europe', 
                      'Iran':'Asia',
                      'Australia':'Australia', 
                      'Brazil':'South America'}

    size = df.groupby(ContinentDict).size()
    sum = df.groupby(ContinentDict).sum()
    mean = df.groupby(ContinentDict).mean()
    std = df.groupby(ContinentDict).std()



    size = size.rename('size')
    sum = sum.rename('sum')
    mean = mean.rename('mean')
    std = std.rename('std')

    df = pd.concat([size, sum, mean, std], axis = 1)

    return df

In [560]:
def anwer_twelve():
    df = answer_one()
    ContinentDict  = {'China':'Asia', 
                          'United States':'North America', 
                          'Japan':'Asia', 
                          'United Kingdom':'Europe', 
                          'Russian Federation':'Europe', 
                          'Canada':'North America', 
                          'Germany':'Europe', 
                          'India':'Asia',
                          'France':'Europe', 
                          'South Korea':'Asia', 
                          'Italy':'Europe', 
                          'Spain':'Europe', 
                          'Iran':'Asia',
                          'Australia':'Australia', 
                          'Brazil':'South America'}

    df['Continent'] = df.index.to_series().map(ContinentDict)

    df['Bins'] = pd.cut(df['% Renewable'], 5)

    df = df[['Continent', 'Bins']]

    return df.groupby(['Continent', 'Bins']).size()

In [643]:
def answer_thirteen():
    df = answer_one()
    df = df[['Energy Supply', 'Energy Supply per Capita']]
    df['Population'] = df['Energy Supply'] / df['Energy Supply per Capita']
    df = df['Population']
    convert_pop = []
    for item in df:
        a, b = str(item).split(sep='.')
        a = a[::-1]
        new_number = []
        count = 1
        for digit in a:
            if count != 3:
                new_number.append(digit)
                count += 1
            else:
                new_number.append(digit)
                new_number.append(',')
                count = 1

        if new_number[-1] == ',':
            new_number.pop(-1)        
        new_number  = ''.join(new_number[::-1])    
        convert_pop.append(new_number+'.'+b)

    PopEst = pd.Series(convert_pop, index = df.index)
    return PopEst